dataset_name: glue_sst2
dataset_description: Binary sentiment detection
adapter_ui_name: Sentiment Detection (SST2)
adapter_category: Sentiment Detection
metric_name: binary_accuracy_flex
split_column_value: 1
data_path: glue_sst2_full.csv
training_data: glue_sst2_full.csv
target_col: label
dataset_link: https://huggingface.co/datasets/glue/viewer/sst2
dataset: s3://tim-adapterland/glue_sst2_full.csv
split: validation
split_column: split
split_column_value: 1
prompt_template: >-
  Given the following sentence:


  "{sentence}"


  Respond with 0 if the sentiment of the sentence is negative and 1 if the
  sentiment of the sentence is positive.
expected_output_format: number
input_columns: sentence
num_examples:
  train: 67349
  validation: 872
  test: 1821
split_used_for_evaluation: validation
