dataset_name: glue_qqp
dataset_description: Do the questions have the same meaning?
adapter_ui_name: Question Comparison (QQP)
adapter_category: Academic Benchmarks
metric_name: binary_accuracy_flex
split_column_value: 1
data_path: glue_qqp_full.csv
training_data: glue_qqp_full.csv
target_col: label
dataset_link: https://huggingface.co/datasets/glue/viewer/qqp
dataset: s3://tim-adapterland/glue_qqp_full.csv
split: validation
split_column: split
split_column_value: 1
prompt_template: >-
  You are given two questions below, Question 1 and Question 2. If the two
  questions are semantically equivalent, please return 1. Otherwise, please
  return 0.


  ### Question 1: {question1}


  ### Question 2: {question2}


  ### Label: 
expected_output_format: number
input_columns: question1, question2
num_examples:
  train: 363846
  validation: 40430
  test: 390965
split_used_for_evaluation: validation
