dataset_name: glue_mrpc
dataset_description: Do the sentences have the same meaning?
adapter_ui_name: Sentence Comparison (MRPC)
adapter_category: Academic Benchmarks
metric_name: mrpc_accuracy
split_column_value: 1
data_path: glue_mrpc_full.csv
training_data: glue_mrpc_full.csv
target_col: label
dataset_link: https://huggingface.co/datasets/glue/viewer/mrpc
dataset: s3://tim-adapterland/glue_mrpc_full.csv
split: validation
split_column: split
split_column_value: 1
prompt_template: >-
  You are given two sentences below, Sentence 1 and Sentence 2. If the two
  sentences are semantically equivalent, please return 1. Otherwise, please
  return 0.


  ### Sentence 1: {sentence1}


  ### Sentence 2: {sentence2}


  ### Label: 
expected_output_format: number
input_columns: sentence1, sentence2
num_examples:
  train: 3668
  validation: 408
  test: 1725
split_used_for_evaluation: validation
